- name: Kubernetes
  hosts: remote
  remote_user: "{{REMOTE_USER}}"
  vars:
      ansible_python_interpreter: /usr/bin/python3
      ansible_user: "{{REMOTE_USER}}"
      ansible_password: "{{REMOTE_PASSWORD}}"
  tasks:
      - name: Environment setup
        ansible.builtin.copy:
            src: server/.env
            dest: /Users/mananmalhotra/expense_tracker/server/.env
      - name: Login in docker hub with user
        community.general.docker_login:
            username: "{{DOCKER_HUB_USER}}"
            password: "{{DOCKER_HUB_PASSWORD}}"
      - name: Delete pods if running2
        ansible.builtin.shell: /usr/local/bin/kubectl delete -f /Users/mananmalhotra/expense_tracker/server/kubernetes.yml
        ignore_errors: true
      - name: Sleep
        ansible.builtin.shell: sleep 30
      - name: Delete Docker image
        community.general.docker_image:
            name: manan80malhotra/expense_tracker
            tag: latest
            state: absent
        ignore_errors: true
      - name: Build Docker image
        community.general.docker_image:
            name: manan80malhotra/expense_tracker
            tag: latest
            source: build
            build:
                path: /Users/mananmalhotra/expense_tracker/server/
                dockerfile: Dockerfile
      - name: Push Docker image to Docker Hub
        community.general.docker_image:
            name: manan80malhotra/expense_tracker
            tag: latest
            push: yes
            source: local
      - name: Install Helm
        command: /opt/homebrew/bin/brew install helm
      - name: Install ngrok Ingress Controller & Creating namespace
        ansible.builtin.shell: /opt/homebrew/bin/helm upgrade -i ngrok-ingress-controller ngrok/kubernetes-ingress-controller --namespace ngrok-ingress-controller --create-namespace --set credentials.apiKey="{{APIKEY}}" --set credentials.authtoken="{{AUTHTOKEN}}"
        ignore_errors: true
      - name: Create pods
        ansible.builtin.shell: /usr/local/bin/kubectl create -f /Users/mananmalhotra/expense_tracker/server/kubernetes.yml
